### ISSUE TITLE
Automatic documentation generation

### ISSUE THREAD

**Issue by embeddedt** [littlevgl/doc#3]
I am concerned that people will submit pull requests without regenerating the documentation. How do you plan to handle that?

I was thinking that having some method of auto-generating documentation after a push would be nice, but I'm not sure if that can be done without a server running 24/7. :confused:

**Comment by kisvegabor** [comment]
> I was thinking that having some method of auto-generating documentation after a push would be nice, but I'm not sure if that can be done without a server running 24/7. 

I've just learned that `events` are generated on push, pull, issue open etc. and an HTTP post can be sent to a server which can make a new push with the re-generated documentation. However, yes, it would require a server which can run `node.js` and `gwtc`.

**Comment by embeddedt** [comment]
@kisvegabor Maybe it is simpler to just regenerate the documentation every time a pull request is merged.

**Comment by kisvegabor** [comment]
I agree!
